site_name: RTM Economic Anlaysis
site_url: 'https://translinkforecasting.github.io/rtmdoc'
site_description: 'RTM documentation for users and developers.'
site_author: 'TransLink Forecasting'
repo_url: 'https://github.com/TransLinkForecasting/rtmdoc'
edit_uri: ""
copyright: 'Copyright &copy; 2020 TransLink Forecasting'
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
nav:
    - 'User Guide':
            - example.md
    - About:
            - about/contributing.md
            # - about/release-notes.md
            # - about/license.md
extra_css:
    - css/extra.css
markdown_extensions:
    -
        toc:
            permalink: true
    - admonition
    - def_list
plugins:
    - search
google_analytics:
    - ""
    - auto
